CREATE TABLE Luxville.USER
(
  FIRST_NAME VARCHAR(50) NOT NULL,
  LAST_NAME VARCHAR(50) NOT NULL,
  COUNTRY_CODE VARCHAR(5) NOT NULL,
  PHONE_NUMBER VARCHAR(15) NOT NULL,
  USER_ID INT AUTO_INCREMENT UNIQUE NOT NULL,
  PRIMARY KEY (USER_ID),
  UNIQUE (COUNTRY_CODE, PHONE_NUMBER)
);

CREATE TABLE Luxville.TRANSACTION
(
  TRANSACTION_ID INT AUTO_INCREMENT UNIQUE NOT NULL,
  PRIMARY KEY (TRANSACTION_ID)
);

CREATE TABLE Luxville.EXTERNAL_USER
(
  USER_ID INT AUTO_INCREMENT NOT NULL,
  RATING FLOAT NOT NULL,
  PRIMARY KEY (USER_ID),
  FOREIGN KEY (USER_ID) REFERENCES Luxville.USER(USER_ID) ON DELETE CASCADE
);
CREATE TABLE Luxville.BUYER
(
  BUYER_SSN VARCHAR(20) UNIQUE NOT NULL,
  BUYER_AREA VARCHAR(100) NOT NULL,
  USER_ID INT AUTO_INCREMENT NOT NULL,
  PRIMARY KEY (USER_ID),
  FOREIGN KEY (USER_ID) REFERENCES Luxville.EXTERNAL_USER(USER_ID) ON DELETE CASCADE
);

CREATE TABLE Luxville.SELLER
(
  SELLER_SSN VARCHAR(20) UNIQUE NOT NULL,
  SELLER_AREA VARCHAR(100) NOT NULL,
  USER_ID INT AUTO_INCREMENT NOT NULL,
  PRIMARY KEY (USER_ID),
  FOREIGN KEY (USER_ID) REFERENCES Luxville.EXTERNAL_USER(USER_ID) ON DELETE CASCADE
);

CREATE TABLE Luxville.OWNER
(
  USER_ID INT AUTO_INCREMENT NOT NULL,
  PRIMARY KEY (USER_ID),
  FOREIGN KEY (USER_ID) REFERENCES Luxville.EXTERNAL_USER(USER_ID) ON DELETE CASCADE
);
CREATE TABLE Luxville.CLIENT
(
  NEED_PROPERTY_FEATURES TEXT,
  PROVIDE_PROPERTY_FEATURES TEXT,
  USER_ID INT NOT NULL,
  PRIMARY KEY (USER_ID),
  FOREIGN KEY (USER_ID) REFERENCES Luxville.EXTERNAL_USER(USER_ID) ON DELETE CASCADE
);

CREATE TABLE Luxville.SYSTEM_USER
(
  EMAIL VARCHAR(100) UNIQUE NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL,
  USER_ID INT NOT NULL,
  PRIMARY KEY (USER_ID),
  FOREIGN KEY (USER_ID) REFERENCES Luxville.USER(USER_ID) ON DELETE CASCADE
);

CREATE TABLE Luxville.ROLE
(
  ROLE_ID INT AUTO_INCREMENT NOT NULL,
  CAN_IMPORT_EXPORT_TRANSACTIONS BOOLEAN NOT NULL,
  CAN_VIEW_TRANSACTIONS BOOLEAN NOT NULL,
  CAN_EDIT_TRANSACTIONS BOOLEAN NOT NULL,
  CAN_DELETE_USER BOOLEAN NOT NULL,
  CAN_CREATE_TRANSACTIONS BOOLEAN NOT NULL,
  CAN_EDIT_AUDIT_LOG BOOLEAN NOT NULL,
  CAN_EXPORT_AUDIT_LOG BOOLEAN NOT NULL,
  CAN_MANAGE_ROLES BOOLEAN NOT NULL,
  CAN_DELETE_TRANSACTIONS BOOLEAN NOT NULL,
  CAN_CREATE_USER BOOLEAN NOT NULL,
  CAN_EDIT_USERS BOOLEAN NOT NULL,
  CAN_VIEW_AUDIT_LOG BOOLEAN NOT NULL,
  ROLE_NAME VARCHAR(50) NOT NULL,
  USER_ID INT NOT NULL,
  PRIMARY KEY (ROLE_ID),
  FOREIGN KEY (USER_ID) REFERENCES Luxville.SYSTEM_USER(USER_ID),
  UNIQUE (ROLE_NAME)
);
CREATE TABLE Luxville.PROPERTY
(
  PROPERTY_ID VARCHAR(20) NOT NULL,
  FOR_RENT BOOLEAN NOT NULL,
  FOR_SALE BOOLEAN NOT NULL,
  PRICE FLOAT NOT NULL,
  PAID_AMOUNT FLOAT NOT NULL DEFAULT 0.0,
  MY_CUT FLOAT NOT NULL DEFAULT 0.0,
  STATUS INT NOT NULL DEFAULT 1,
  AREA TEXT NOT NULL,
  LISTING_DATE TIMESTAMP NOT NULL,
  MEDIA_LINK VARCHAR(2048) NULL,
  IS_INSTALLMENT_AVAILABLE BOOLEAN NOT NULL DEFAULT FALSE,
  INSTALLMENT_DURATION_MONTHS INT NULL,
  DOWN_PAYMENT FLOAT NULL,
  MONTHLY_PAYMENT FLOAT NULL,
  INTEREST_RATE FLOAT NULL,
  PAYMENT_START_DATE TIMESTAMP NULL,
  LATITUDE FLOAT NOT NULL,
  LONGITUDE FLOAT NOT NULL,
  ADDRESS_LINK VARCHAR(2048) NOT NULL,
  OWNER_ID INT,
  SELLER_ID INT,
  PRIMARY KEY (PROPERTY_ID),
  FOREIGN KEY (OWNER_ID) REFERENCES Luxville.OWNER(USER_ID) ON DELETE CASCADE,
  FOREIGN KEY (SELLER_ID) REFERENCES Luxville.SELLER(USER_ID) ON DELETE CASCADE
);

CREATE TABLE Luxville.DEAL
(
  DEAL_ID INT AUTO_INCREMENT UNIQUE NOT NULL,
  DEAL_DATE TIMESTAMP NOT NULL,
  BUYER_ID INT NOT NULL,
  SELLER_ID INT NOT NULL,
  AGENT_ID INT NOT NULL,
  PRIMARY KEY (DEAL_ID),
  FOREIGN KEY (BUYER_ID) REFERENCES Luxville.BUYER(USER_ID) ON DELETE CASCADE,
  FOREIGN KEY (SELLER_ID) REFERENCES Luxville.SELLER(USER_ID) ON DELETE CASCADE,
  FOREIGN KEY (AGENT_ID) REFERENCES Luxville.SYSTEM_USER(USER_ID)
);
CREATE TABLE Luxville.APPOINTMENT
(
  APPOINTMENT_ID INT AUTO_INCREMENT UNIQUE NOT NULL,
  PROPERTY_ID VARCHAR(20),
  SCHEDULED_TIME TIMESTAMP NOT NULL,
  STATUS INT NOT NULL DEFAULT 0,
  INITIATED_AT TIMESTAMP NULL,
  CLIENT_ID INT NOT NULL,
  AGENT_ID INT NOT NULL,
  PRIMARY KEY (APPOINTMENT_ID),
  FOREIGN KEY (CLIENT_ID) REFERENCES Luxville.CLIENT(USER_ID) ON DELETE CASCADE,
  FOREIGN KEY (AGENT_ID) REFERENCES Luxville.SYSTEM_USER(USER_ID) ON DELETE CASCADE,
  FOREIGN KEY (PROPERTY_ID) REFERENCES Luxville.PROPERTY(PROPERTY_ID) ON DELETE CASCADE
);

CREATE TABLE Luxville.AUDITLOG
(
  ACTION VARCHAR(100) NOT NULL,
  AUDITLOG_ID INT AUTO_INCREMENT NOT NULL,
  USER_ID INT NOT NULL,
  PRIMARY KEY (AUDITLOG_ID),
  FOREIGN KEY (USER_ID) REFERENCES Luxville.SYSTEM_USER(USER_ID)
);

CREATE TABLE Luxville.REPORT
(
  REPORT_ID INT AUTO_INCREMENT UNIQUE NOT NULL,
  REPORT_TITLE VARCHAR(255) NOT NULL,
  REPORT_DESCRIPTION TEXT NULL,
  REPORT_TYPE VARCHAR(50) NULL,
  REPORT_FORMAT VARCHAR(50) NOT NULL,
  FILE_PATH VARCHAR(255) NULL,
  STATUS INT NOT NULL DEFAULT 1,
  GENERATED_AT TIMESTAMP NOT NULL,
  REVIEWED_AT TIMESTAMP NULL,
  USER_ID INT NOT NULL,
  PRIMARY KEY (REPORT_ID),
  FOREIGN KEY (USER_ID) REFERENCES Luxville.SYSTEM_USER(USER_ID)
);

CREATE TABLE Luxville.REVENUE
(
  REVENUE_ID INT AUTO_INCREMENT UNIQUE NOT NULL,
  DESCRIPTION TEXT NULL,
  AMOUNT FLOAT NOT NULL DEFAULT 0.0,
  RECORDED_AT TIMESTAMP NOT NULL,
  DEAL_ID INT NOT NULL,
  TRANSACTION_ID INT NOT NULL,
  PRIMARY KEY (REVENUE_ID),
  FOREIGN KEY (DEAL_ID) REFERENCES Luxville.DEAL(DEAL_ID),
  FOREIGN KEY (TRANSACTION_ID) REFERENCES Luxville.TRANSACTION(TRANSACTION_ID) ON DELETE CASCADE
);

CREATE TABLE Luxville.EXPENSE
(
  EXPENSE_ID INT AUTO_INCREMENT UNIQUE NOT NULL,
  DESCRIPTION TEXT NULL,
  AMOUNT FLOAT NOT NULL DEFAULT 0.0,
  USER_ID INT NOT NULL,
  TRANSACTION_ID INT NOT NULL,
  PRIMARY KEY (EXPENSE_ID),
  FOREIGN KEY (USER_ID) REFERENCES Luxville.SYSTEM_USER(USER_ID),
  FOREIGN KEY (TRANSACTION_ID) REFERENCES Luxville.TRANSACTION(TRANSACTION_ID) ON DELETE CASCADE
);

CREATE TABLE Luxville.SELLING_DEAL
(
  SELLING_DEAL_ID INT AUTO_INCREMENT UNIQUE NOT NULL,
  PAYMENT_TYPE VARCHAR(50) NOT NULL,
  NEGOTIABLE BOOLEAN NOT NULL DEFAULT FALSE,
  OWNERSHIP_TYPE VARCHAR(100),
  PROPERTY_TITLE_DEED TEXT NOT NULL,
  LEGAL_CLEARANCE BOOLEAN NOT NULL DEFAULT FALSE,
  FINAL_PRICE FLOAT NOT NULL DEFAULT 0.0,
  ASKING_PRICE FLOAT NOT NULL DEFAULT 0.0,
  PAID_AMOUNT FLOAT NOT NULL DEFAULT 0.0,
  COMMISSION_RATE FLOAT NOT NULL DEFAULT 0.0,
  DEAL_ID INT NOT NULL,
  PRIMARY KEY (DEAL_ID),
  FOREIGN KEY (DEAL_ID) REFERENCES Luxville.DEAL(DEAL_ID) ON DELETE CASCADE,
  UNIQUE (SELLING_DEAL_ID)
);
CREATE TABLE Luxville.RENTING_DEAL
(
  RENTING_DEAL_ID INT AUTO_INCREMENT UNIQUE NOT NULL,
  START_DATE TIMESTAMP NOT NULL,
  SECURITY_AMOUNT FLOAT NULL,
  MONTHLY_RENT FLOAT NOT NULL DEFAULT 0.0,
  PAYMENT_FREQUENCY INT NOT NULL DEFAULT 0,
  LEASE_DURATION INT NOT NULL DEFAULT 0,
  UTILITIES_INCLUDED TEXT NULL,
  RENTAL_CONDITIONS TEXT NULL,
  DEAL_ID INT NOT NULL,
  PRIMARY KEY (DEAL_ID),
  FOREIGN KEY (DEAL_ID) REFERENCES Luxville.DEAL(DEAL_ID) ON DELETE CASCADE,
  UNIQUE (RENTING_DEAL_ID)
);

CREATE TABLE Luxville.HOUSE
(
  PROPERTY_ID VARCHAR(20),
  NUMBER_OF_BATHROOMS INT NOT NULL,
  NUMBER_OF_BEDROOMS INT NOT NULL,
  NUMBER_OF_FLOORS INT,
  HAS_GARAGE BOOLEAN,
  HAS_GARDEN BOOLEAN,
  YEAR_BUILT INT,
  HEATING_TYPE VARCHAR(50),
  COOLING_TYPE VARCHAR(50),
  IS_FURNISHED BOOLEAN,
  BACKYARD_AREA FLOAT,
  FLOORING_TYPE VARCHAR(50),
  ROOF_TYPE VARCHAR(50),
  NETWORK_INFRASTRUCTURE TEXT NULL,
  HAS_LANDLINE BOOLEAN,
  PRIMARY KEY (PROPERTY_ID),
  FOREIGN KEY (PROPERTY_ID) REFERENCES Luxville.PROPERTY(PROPERTY_ID) ON DELETE CASCADE
);
CREATE TABLE Luxville.APARTMENT
(
  PROPERTY_ID VARCHAR(20),
  FLOOR_NUMBER INT NOT NULL,
  UNIT_NUMBER INT NOT NULL,
  NUMBER_OF_BATHROOMS INT NOT NULL,
  NUMBER_OF_BEDROOMS INT NOT NULL,
  BUILDING_NAME VARCHAR(100),
  HAS_ELEVATOR BOOLEAN,
  MONTHLY_MAINTENANCE_FEE FLOAT,
  IS_FURNISHED BOOLEAN,
  HAS_BALCONY BOOLEAN,
  VIEW_TYPE TEXT NULL,
  NETWORK_INFRASTRUCTURE TEXT NULL,
  HAS_LANDLINE BOOLEAN,
  PRIMARY KEY (PROPERTY_ID),
  FOREIGN KEY (PROPERTY_ID) REFERENCES Luxville.PROPERTY(PROPERTY_ID) ON DELETE CASCADE
);

CREATE TABLE Luxville.STUDIO
(
  PROPERTY_ID VARCHAR(20),
  FLOOR_NUMBER INT NOT NULL,
  APARTMENT_NAME VARCHAR(100) NOT NULL,
  IS_FURNISHED BOOLEAN,
  HAS_KITCHENETTE BOOLEAN,
  HAS_BALCONY BOOLEAN,
  MONTHLY_MAINTENANCE_FEE FLOAT,
  HAS_LANDLINE BOOLEAN,
  PRIMARY KEY (PROPERTY_ID),
  FOREIGN KEY (PROPERTY_ID) REFERENCES Luxville.PROPERTY(PROPERTY_ID) ON DELETE CASCADE
);

CREATE TABLE Luxville.OFFICE
(
  PROPERTY_ID VARCHAR(20),
  FLOOR_NUMBER INT NOT NULL,
  BUILDING_NAME VARCHAR(100) NOT NULL,
  NUMBER_OF_ROOMS INT NOT NULL DEFAULT 0,
  MEETING_ROOMS INT,
  IS_FURNISHED BOOLEAN,
  HAS_RECEPTION_AREA BOOLEAN,
  HAS_PARKING BOOLEAN,
  MONTHLY_MAINTENANCE_FEE FLOAT,
  HAS_LANDLINE BOOLEAN,
  NETWORK_INFRASTRUCTURE TEXT NULL,
  PRIMARY KEY (PROPERTY_ID),
  FOREIGN KEY (PROPERTY_ID) REFERENCES Luxville.PROPERTY(PROPERTY_ID) ON DELETE CASCADE
);

CREATE TABLE Luxville.LAND
(
  PROPERTY_ID VARCHAR(20),
  LAND_TYPE VARCHAR(100) NOT NULL DEFAULT 'Residential',
  ZONING_INFO TEXT NOT NULL,
  BUILDABLE_AREA BOOLEAN NOT NULL DEFAULT TRUE,
  PLOT_NUMBER VARCHAR(20) NOT NULL,
  TOPOGRAPHY VARCHAR(50),
  ROAD_ACCESS TEXT,
  PRIMARY KEY (PROPERTY_ID),
  FOREIGN KEY (PROPERTY_ID) REFERENCES Luxville.PROPERTY(PROPERTY_ID) ON DELETE CASCADE
);
